### ISSUE TITLE
Error Authorization

### ISSUE THREAD

**Issue by n-osennij** [tioffs/InstaLite#1]
При попытке авторизации получаю Error Authorization. При этом в веб версии инстраграма приходит оповещение о подозрительном входе в аккаунт. Я подтверждаю, что это я. Но при следующей попытке залогиниться всё повторяется.

Использую windows 10, laragon в качестве локального сервера, php 7.3.13, laravel 6.х

```
public function test()
{
    $instagram = new InstaLite(env('INSTA_LOGIN'), env('INSTA_PASSWORD'));

    $img = '6NILaD3a18RN95gwQENq7zMQ6mDaVkMp1LvyrpHs.jpeg';

    $instagram->uploadPhoto($this->getStorageOriginalImgPath($img), 'text #hashtag');
}

private function getStorageOriginalImgPath(string $img)
{
    return storage_path("app\public\images\originals\\".$img);
}
```

**Comment by tioffs** [comment]
отключи 2FA, я пока не сделал авторизацию с подтверждением

**Comment by n-osennij** [comment]
> отключи 2FA, я пока не сделал авторизацию с подтверждением

а я и не использую двухфакторную 

![image](https://user-images.githubusercontent.com/17576299/73719619-091bae00-4731-11ea-9608-145f3b67ccb1.png)

Вот так отображается попытка входа
![image](https://user-images.githubusercontent.com/17576299/73719764-67e12780-4731-11ea-9674-7279cffd0577.png)

**Comment by tioffs** [comment]
используешь прокси? возможно прокси косячный.
**или** [попробуй поставить юзер агент в InstaLite.php](https://github.com/tioffs/InstaLite/blob/f047184e27ddf4138ed6f073b60931f94bd301c0/src/InstaLite/InstaLite.php#L29)

**Comment by dgaenko** [comment]
Аналогично - не получилось авторизоваться.

> PHP Fatal error:  Uncaught InstaLite\Exception: Error Authorization in D:\_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php:86
Stack trace:
#0 D:\_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php(59): InstaLite\InstaLite->__login()
#1 D:\_SCRIPTS_\sender.php(5): InstaLite\InstaLite->__construct($login, $passwd)
#2 {main}
  thrown in D:\_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php on line 86

пробовал из консоли win7 и на ubuntu server

**Comment by tioffs** [comment]
> Аналогично - не получилось авторизоваться.
> 
> > PHP Fatal error:  Uncaught InstaLite\Exception: Error Authorization in D:_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php:86
> > Stack trace:
> > #0 D:_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php(59): InstaLite\InstaLite->__login()
> > #1 D:_SCRIPTS_\sender.php(5): InstaLite\InstaLite->__construct($login, $passwd)
> > #2 {main}
> > thrown in D:_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php on line 86
> 
> пробовал из консоли win7 и на ubuntu server

через пару дней обнова так что там все нормально будет

**Comment by dgaenko** [comment]
понял, спасибо

**Comment by n-osennij** [comment]
> > Аналогично - не получилось авторизоваться.
> > > PHP Fatal error:  Uncaught InstaLite\Exception: Error Authorization in D:_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php:86
> > > Stack trace:
> > > #0 D:_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php(59): InstaLite\InstaLite->__login()
> > > #1 D:_SCRIPTS_\sender.php(5): InstaLite\InstaLite->__construct($login, $passwd)
> > > #2 {main}
> > > thrown in D:_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php on line 86
> > 
> > 
> > пробовал из консоли win7 и на ubuntu server
> 
> через пару дней обнова так что там все нормально будет

есть сподвижки?

**Comment by dgaenko** [comment]
нет - пришлось выкинуть

**Comment by vpodorozh** [comment]
У меня была такая же проблема - но я поставил дефолтное значение для прокси null и кажись заработало.
`$instagram = new InstaLite("zzz", "zzz", null, true);`

В примере в README `$instagram = new InstaLite("zzz", "zzz", "proxy", true);` - что по видимому не работает.

**Comment by tioffs** [comment]
> У меня была такая же проблема - но я поставил дефолтное значение для прокси null и кажись заработало.
> `$instagram = new InstaLite("zzz", "zzz", null, true);`
> 
> В примере в README `$instagram = new InstaLite("zzz", "zzz", "proxy", true);` - что по видимому не работает.
 
Ваш прокси скорее всего в блоке у инстаграм или используется несколькими аккаунтами

**Comment by bo-co** [comment]
С авторизацией, действительно, есть проблемы
«Мы обнаружили подозрительную попытку входа» — такое вот сообщение появляется на сайте, на которое приходится отвечать «Это я».

$instagram = new InstaLite("username", "password", null, true) крашится в Fatal error: Uncaught InstaLite\Exception: Error Authorization Stack trace: 
#0 .../instalite.php(59): InstaLite\InstaLite->__login()
#1 .../instalite.php(8): InstaLite\InstaLite->__construct('username', 'password', NULL, true)
#2 {main} thrown in .../instalite.php on line 86

**Comment by integratorSystech** [comment]
при попытке использовать пример из readme.md получаю ошибку 
ParseError
syntax error, unexpected '?'
1. in ../instalite/src/InstaLite/InstaLite.php at line 157

**Comment by APTEMOH** [comment]
> при попытке использовать пример из readme.md получаю ошибку
> ParseError
> syntax error, unexpected '?'
> 
> 1. in ../instalite/src/InstaLite/InstaLite.php at line 157

PHP version > 7.2

**Comment by APTEMOH** [comment]
> > Аналогично - не получилось авторизоваться.
> > > PHP Fatal error:  Uncaught InstaLite\Exception: Error Authorization in D:_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php:86
> > > Stack trace:
> > > #0 D:_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php(59): InstaLite\InstaLite->__login()
> > > #1 D:_SCRIPTS_\sender.php(5): InstaLite\InstaLite->__construct($login, $passwd)
> > > #2 {main}
> > > thrown in D:_SCRIPTS_\vendor\tioffs\instalite\src\InstaLite\InstaLite.php on line 86
> > 
> > 
> > пробовал из консоли win7 и на ubuntu server
> 
> через пару дней обнова так что там все нормально будет

Либа умерла?
Не пускает в авторизации (

**Comment by n-osennij** [comment]
Не работает. При попытке авторизации выдаёт Error Authorization. А на телефон приходит смс с кодом, который, судя по всему, нужно ввести для авторизации.

**Comment by tioffs** [comment]
> Не работает. При попытке авторизации выдаёт Error Authorization. А на телефон приходит смс с кодом, который, судя по всему, нужно ввести для авторизации.

Отключи 2FA авторизуйся и все будет ок

**Comment by ph1ex0n** [comment]
на авторизации, ни 2fa ни прокси не использую
>php index.php 
PHP Fatal error:  Uncaught InstaLite\Exception: Error Authorization in /var/www/instalite/vendor/tioffs/instalite/src/InstaLite/InstaLite.php:86
Stack trace:
#0 /var/www/instalite/vendor/tioffs/instalite/src/InstaLite/InstaLite.php(59): InstaLite\InstaLite->__login()
#1 /var/www/instalite/index.php(13): InstaLite\InstaLite->__construct()
#2 {main}
  thrown in /var/www/instalite/vendor/tioffs/instalite/src/InstaLite/InstaLite.php on line 86

**Comment by tioffs** [comment]
> на авторизации, ни 2fa ни прокси не использую
> 
> > php index.php
> > PHP Fatal error:  Uncaught InstaLite\Exception: Error Authorization in /var/www/instalite/vendor/tioffs/instalite/src/InstaLite/InstaLite.php:86
> > Stack trace:
> > #0 /var/www/instalite/vendor/tioffs/instalite/src/InstaLite/InstaLite.php(59): InstaLite\InstaLite->__login()
> > #1 /var/www/instalite/index.php(13): InstaLite\InstaLite->__construct()
> > #2 {main}
> > thrown in /var/www/instalite/vendor/tioffs/instalite/src/InstaLite/InstaLite.php on line 86

**смени**
[user agent](https://github.com/tioffs/InstaLite/blob/f047184e27ddf4138ed6f073b60931f94bd301c0/src/InstaLite/InstaLite.php#L29)
[версию инстаграмм](https://github.com/tioffs/InstaLite/blob/f047184e27ddf4138ed6f073b60931f94bd301c0/src/InstaLite/InstaLite.php#L30)

**Comment by ph1ex0n** [comment]
на что менять?

**Comment by tioffs** [comment]
> на что менять?

заходишь на сайт инстаграмма открываешь панель разработчика и смотришь исходящий трафик там должны быть эти заголовки.

**Comment by APTEMOH** [comment]
> отключи 2FA, я пока не сделал авторизацию с подтверждением

Планируете развивать библиотеку?

**Comment by tioffs** [comment]
> Планируете развивать библиотеку?

нет смысла когда есть полностью реализованные ищите внимательно
