### ISSUE TITLE
A few photos

### ISSUE THREAD

**Issue by pbadun** [tioffs/InstaLite#3]
Good day. How to send multiple photos in one message?

**Comment by tioffs** [comment]
Call this method as many times as you need to upload photos
https://github.com/tioffs/InstaLite/blob/f047184e27ddf4138ed6f073b60931f94bd301c0/src/InstaLite/InstaLite.php#L162-L183
Here you need to pass an array of responses received earlier
https://github.com/tioffs/InstaLite/blob/f047184e27ddf4138ed6f073b60931f94bd301c0/src/InstaLite/InstaLite.php#L188
```php
@example
-> addParam( 'upload_id' , [$response1[ 'upload_id' ],$response2[ 'upload_id' ],$response3[ 'upload_id' ]])
```

**Comment by pbadun** [comment]
Not work.

Send: 
Array
(
    [0] => 1622750604563
    [1] => 1622750606010
    [2] => 1622750607029
)

Result:

Uncaught InstaLite\Exception: Error save post: {"message":"Missing info.","status":"fail"}

**Comment by pbadun** [comment]
$upload_id = [];
        foreach ($ph as $photo) {
            if (!file_exists($photo)) {
                throw new Exception("File [$photo] not found");
            }
            $photo_id = round(microtime(true) * 1000);
            $file_temp = __DIR__ . '/' . $this->uuid4();
            list($width, $height, $image_type) = getimagesize(realpath($photo));
            $srcImage = ImageCreateFromJPEG($photo);
            $resImage = ImageCreateTrueColor($width, $height);
            ImageCopyResampled($resImage, $srcImage, 0, 0, 0, 0, $width, $height, $width, $height);
            ImageJPEG($srcImage, $file_temp, 100);
            ImageDestroy($srcImage);

            $response = Request::post($this->web . 'rupload_igphoto/fb_uploader_' . $photo_id)
                ->addHead('content-type', 'image/jpg')
                ->addHead('x-entity-name', 'fb_uploader_' . $photo_id)
                ->addHead('offset', 0)
                ->addHead('user-agent', 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X; ru-RU) AppleWebKit/537.36 (KHTML, like Gecko)  Version/11.4.1 Mobile/15G77 Safari/537.36 Puffin/5.2.2IP')
                ->addHead('x-entity-length', filesize($file_temp))
                ->addHead('x-instagram-rupload-params', '{"media_type":1,"upload_id":"' . $photo_id . '","upload_media_height":' . $height . ',"upload_media_width":' . $width . '}')
                ->addFile($file_temp)
                ->json(true);
            unlink($file_temp);
            if (!isset($response['upload_id'], $response['status']) && $response['status'] != 'ok') {
                throw new Exception("Error upload file: " . \json_encode($response));
            }
            $this->__log('upload file success: ' . \json_encode($response));
            $upload_id[] = $response['upload_id'];
        }
        print_r($upload_id);


        $response = Request::post($this->web . 'create/configure/')
            ->addHead('content-type', 'application/x-www-form-urlencoded')
            ->addHead('user-agent', 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X; ru-RU) AppleWebKit/537.36 (KHTML, like Gecko)  Version/11.4.1 Mobile/15G77 Safari/537.36 Puffin/5.2.2IP')
            ->addParam('upload_id', $upload_id)
            ->addParam('caption', $message)
            ->addParam('usertags', '')
            ->addParam('custom_accessibility_caption', '')
            ->addParam('retry_timeout', '')
            ->json(true);

        print_r($response);
